# Generated by Django 5.1.2 on 2024-11-23 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datos_vehiculo', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_siniestro', models.CharField(choices=[('ChoqueObjeto', 'ChoqueObjeto'), ('ChoquePersona', 'ChoquePersona'), ('ChoqueVehiculo', 'ChoqueVehiculo'), ('Robo', 'Robo'), ('RoboParcial', 'RoboParcial'), ('Incendio', 'Incendio'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'siniestro',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuil', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('razon_social', models.CharField(max_length=45)),
                ('telefono', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='EstadoPoliza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_poliza',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('numero_registro', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('telefono', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='TipoCobertura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cobertura',
            },
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'uso',
            },
        ),
        migrations.CreateModel(
            name='ChoqueObjeto',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('numero_denuncia', models.IntegerField(unique=True)),
                ('condicion_climatica', models.TextField()),
            ],
            options={
                'db_table': 'choque_objeto',
            },
        ),
        migrations.CreateModel(
            name='ChoquePersona',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('persona_chocada', models.TextField()),
                ('numero_denuncia', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'choque_persona',
            },
        ),
        migrations.CreateModel(
            name='Incendio',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('numero_informe', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'incendio',
            },
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('numero_denuncia', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'robo',
            },
        ),
        migrations.CreateModel(
            name='RoboParcial',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('numero_denuncia', models.IntegerField(unique=True)),
                ('pertenencias_robadas', models.TextField()),
            ],
            options={
                'db_table': 'robo_parcial',
            },
        ),
        migrations.CreateModel(
            name='InformeHeridos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('herido', models.TextField()),
                ('descripcion', models.TextField()),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.siniestro')),
            ],
            options={
                'db_table': 'informe_heridos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('codigo_postal', models.CharField(max_length=45)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.localidad')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='app.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.AddField(
            model_name='siniestro',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros_conductor', to='app.persona'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros_titular', to='app.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.direccion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConductoresEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.persona')),
            ],
            options={
                'db_table': 'conductores_empresa',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('franquicia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estadopoliza')),
                ('tipo_cobertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipocobertura')),
            ],
            options={
                'db_table': 'poliza',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero', models.IntegerField(unique=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poliza')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=45)),
                ('numero_chasis', models.BigIntegerField(unique=True)),
                ('numero_motor', models.CharField(max_length=45, unique=True)),
                ('patente', models.CharField(max_length=45, unique=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.modelo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.tipo')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.persona')),
                ('uso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.uso')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vehiculo'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vehiculo'),
        ),
        migrations.CreateModel(
            name='ChoqueVehiculo',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.siniestro')),
                ('datos_vehiculo_tercero', models.TextField()),
                ('tercero', models.TextField()),
                ('vehiculo_tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo')),
            ],
            options={
                'db_table': 'choque_vehiculo',
            },
        ),
    ]
