# Generated by Django 5.1.2 on 2024-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeheridos',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
